### ISSUE TITLE
Replace canned action to push to nuget with dotnet commands

### ISSUE THREAD

**Issue by JYCabello** [JYCabello/DeFuncto#93]
Example:
```yaml
- name: Package
  run: dotnet pack -c Release -o . GrpcBrowser/GrpcBrowser.csproj
- name: Publish
  run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
```
